spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/turkey-security?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp