spring:

  application:
    name: oauth2-server

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/turkey-security?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    schema:
    - classpath:schema.sql
#    data:
#    - classpath:t_user_data.sql

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    openInView: true
    show-sql: true
    generate-ddl: true
    hibernate:
#      naming:
#        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  redis:
    host: 10.80.3.55
    port: 6379
    password: yfy_otvcloud
    pool:
      min-idle: 1
      max-idle: 20
      max-active: 20
      max-wait: 6000
    database: 0